
#mybatis-plus日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    incomplete-cache-refs:
  global-config:
    db-config:
      id-type: auto
#      table-prefix: tb_
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.proxy.DruidDriver
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/11?serverTimeZone=UTC
      password: 123456
      username: root

#mq
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    template:
      default-destination: ssmp

#rabbitmq
  rabbitmq:
    host: localhost
    port: 5157

#kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: itheima2022

#rocketmq
rocketmq:
  name-server: localhost:9287
  producer:
    group: group_rocket








